source 'https://rubygems.org'

#gem 'omnibus', '~> 2.0.0'
# TODO: get name of a tag which corresponds to a latest ver
gem 'fpm'
gem 'omnibus', :git => 'git://github.com/Scalr/omnibus.git', :branch => 'master'
gem 'omnibus-software', :git => 'git://github.com/Scalr/omnibus-software.git', :branch => 'master'
