source 'https://rubygems.org'

#gem 'omnibus', '~> 2.0.0'
gem 'omnibus', :git => 'git://github.com/levsh/omnibus-ruby.git', :branch => 'master'
gem 'omnibus-software', :git => 'git://github.com/opscode/omnibus-software.git', :branch => 'master'
