source 'https://rubygems.org'

#gem 'omnibus', '~> 2.0.0'
# TODO: get name of a tag which corresponds to a latest ver
gem 'omnibus', :git => 'git://github.com/Scalr/omnibus-ruby.git', :tag => '3.2.0'
gem 'omnibus-software', :git => 'git://github.com/opscode/omnibus-software.git', :branch => 'master'
