#!/bin/bash
#
# Perform necessary scalarizr removal steps
# after package is uninstalled.
#

if ( [ "$1" = '1' ] || [ "$1" = 'upgrade' ] ); 
    echo "scalarizr has been upgraded!"
else
    unlink /etc/init.d/scalarizr 
    unlink /etc/init.d/scalr-upd-client
    echo "scalarizr has been uninstalled!"
fi

exit 0
