#!/bin/bash
#
# Perform necessary scalarizr removal steps
# after package is uninstalled.
#

unlink /etc/init.d/scalarizr 
unlink /etc/init.d/scalr-upd-client

echo "scalarizr has been uninstalled!"

exit 0
