#!/bin/bash
#
# Perform necessary scalarizr setup steps
# prior to installing package.
#

PROGNAME='scalarizr'

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

exit 0
