#!/usr/bin/python

import sys
try:
	from scalarizr.scripts.udev import main
except ImportError, e:
	print >> sys.stderr, "error: %s\n\nPlease make sure that scalarizr is properly installed" % (e)
	sys.exit(1)

main()