#!/usr/bin/php
<?php

class Scalr_Messaging_CryptoTool {
	const CRYPTO_ALGO = MCRYPT_TRIPLEDES;
	const CIPHER_MODE = MCRYPT_MODE_CBC;
	const HASH_ALGO = 'SHA256';
	
	static private $instance;
	
	/**
	 * @return Scalr_Messaging_CryptoTool
	 */
	static function getInstance() {
		if (self::$instance === null) {
			self::$instance = new Scalr_Messaging_CryptoTool();
		}
		return self::$instance;
	}	
	
	private function splitKeyIv ($cryptoKey) {
		$key = substr($cryptoKey, 0, 24);
		//$key = substr($cryptoKey, 0, strlen($cryptoKey) - 8);
		$iv = substr($cryptoKey, -8);
		printf("skey(hex): %s\n", bin2hex($key));
		printf("iv(hex): %s\n", bin2hex($iv));
		  		
		return array($key, $iv);
	}
	
	private function pkcs5Padding ($text, $blocksize) {
	    $pad = $blocksize - (strlen($text) % $blocksize);
    	return $text . str_repeat(chr($pad), $pad);
	}

	
	function encrypt ($string, $cryptoKey) {
		list($key, $iv) = $this->splitKeyIv($cryptoKey);
		$ret = mcrypt_encrypt(self::CRYPTO_ALGO, $key, $this->pkcs5Padding($string, 8), self::CIPHER_MODE, $iv);
		printf("encrypted(hex): %s\n", bin2hex($ret));
		return base64_encode($ret);
	}
	
	function decrypt ($string, $cryptoKey) {
		list($key, $iv) = $this->splitKeyIv($cryptoKey);
		printf("encrypted(hex): %s\n", bin2hex(base64_decode($string)));
		$ret = mcrypt_decrypt(self::CRYPTO_ALGO, $key, base64_decode($string), self::CIPHER_MODE, $iv);
		// Remove padding
		return trim($ret, "\x00..\x1F");		
	}
	
	function sign ($data, $key, $timestamp=null) {
		$date = date("c", $timestamp ? $timestamp : time());
		$canonical_string = $data . $date;
		$hash = base64_encode(hash_hmac(self::HASH_ALGO, $canonical_string, $key, 1));
		return array($hash, $date);
	}
}


$key = base64_decode(trim(file_get_contents(dirname(__FILE__) . "/crypto-key")));
print bin2hex($key) . "\n";
$op = $_SERVER["argv"][1];
$string = $_SERVER["argv"][2] ? $_SERVER["argv"][2] : file_get_contents("php://stdin");

$tool = Scalr_Messaging_CryptoTool::getInstance();
if ($op == "--encrypt" || $op == "-e") {
	print $tool->encrypt($string, $key) . "\n";
} elseif ($op == "--decrypt" || $op == "-d") {
	print $tool->decrypt($string, $key) . "\n";
} else {
	print "E: Unknown operation {$op}\n";
}
